### ISSUE TITLE
Take types into account while serializing MDC values

### ISSUE THREAD

**Issue by vtrbtf** [vy/log4j2-logstash-layout#13]
Hi man !

The lib is helping me a lot. However, it would be awesome if the layout could infer numeric values from MDC. This is something that would help on metrics and aggregations on ES. 
Currently, we can only publish String MDC values. 

If you're too busy, I could open a PR for that. However I dont know where to start

**Comment by vy** [comment]
Thanks for the issue and PR @vtrbtf! And I am glad that the code proves to be useful for you.
The issue is much more wide-spread than just numbers: Apparently I was discarding the Java types (`Object`, `BigDecimal`, `Float`, etc.) of MDC values by initially rendering them to text, which happens to be unfortunately borrowed by your PR as well. I pushed a change to `master`, would you mind verifying if this is indeed what you wanted, please?

**Comment by vtrbtf** [comment]
AWESOME! Thanks 

Are you planning to release a version with that ?

**Comment by vtrbtf** [comment]
@vy That was exactly what I was looking for

**Comment by vy** [comment]
Ok, I will make a new release momentarily.
