### ISSUE TITLE
add Marker support

### ISSUE THREAD

**Issue by FrVaBe** [vy/log4j2-logstash-layout#21]
The LogEvent template variables which can be used inside custom templates do not support Marker ([LogEvent.getMarker()](https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/LogEvent.html#getMarker())). Would be nice if this would be added.

Layout should be done as in the [Log4j2-JSONLayout](https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout):

```xml
  "marker" : {
    "name" : "child",
    "parents" : [ {
      "name" : "parent",
      "parents" : [ {
        "name" : "grandparent"
      } ]
    } ]
  },
```

**Comment by vy** [comment]
Adding `Marker` support with a customizable layout turned out to be a pretty tough job due its recursive nature. After a decent amount of struggle, I decided to only introduce `marker:name`, that is, `LogEvent#getMarker().getName()`. The change is available in 017a95a. @FrVaBe, would you mind telling if this is good enough for your use case, please?

**Comment by FrVaBe** [comment]
@vy Thank you for the implementation, which is certainly sufficient for many purposes. However, I can't rule out that we (or someone on my team) won't use Marker inheritance in the future.
Since we haven't made a final decision on the logging strategy yet, I don't want to claim the full feature here. As far as I can see the library offers a good possibility to use custom structured logging.  :+1:

**Comment by vy** [comment]
Thanks for trying it out @FrVaBe. Then I am leaving the implementation in its current state right now (that is, only plain Marker support without inheritance) and closing the issue.
