### ISSUE TITLE
LogStash Appender Question

### ISSUE THREAD

**Issue by sabareeshkkanan** [vy/log4j2-logstash-layout#24]
I understand this project focuses only on the layout but I am wondering what appender to use instead of appending to a file and then uploading using logstash.

**Comment by vy** [comment]
There are a couple of approaches you can take there. Two prominent ones I know of are as follows:

1. Use [filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-overview.html) to stream log files produced by log4j2 to Logstash.
2. Use [log4j2-redis-appender](https://github.com/vy/log4j2-redis-appender) in combination with [Logstash Redis plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html).

Since the question is not an *issue* of the log42j-logstash-layout, I am closing the ticket. Feel free to comment.
