### ISSUE TITLE
Remove max byte count cap?

### ISSUE THREAD

**Issue by ayush-finix** [vy/log4j2-logstash-layout#67]
I'm not sure if this is an issue or not, so just seeking clarification.

Is there a way to not cap the log size length? For our use case, we'd rather keep all the log messages instead of setting an arbitrary limit. Would it be an issue if we set the maxByte to something really high like 100k (our concern was whether these buffers were allocated for every log message)?

**Comment by vy** [comment]
Hello @ayush-finix, sorry for the late reply.

The code in `master` (hence, the recent releases) allocates thread-local buffers to avoid generating garbage while rendering JSON. At this stage it is not possible to remove the max byte count cap. Though there are a couple of things that I would like to share with you:

- It is not a good practice to remove the cap on the buffer size. I would advise experimenting a bit to find the right setting for your case. Note that this buffer is created per-thread, not per-logging-request and/or -message.

- `LogstashLayout` will be superseded by `JsonTemplateLayout` in the Log4j project itself. `JsonTemplateLayout` is in both `release-2.x` and `master` branches of the core Log4j repository. With the next Log4j 2.x release, we will have a brand new, totally overhauled Log4j JSON layout. There one can chose between a variety of [recycling strategies](https://github.com/apache/logging-log4j2/blob/master/src/site/asciidoc/manual/json-template-layout.adoc.vm#L270). Hence, keep an eye on the upcoming Log4j 2.x release.

I am closing this issue since there is not much to be done. Let me know if you think otherwise.
