### ISSUE TITLE
sleuth logging pattern: pid and defaultvalues

### ISSUE THREAD

**Issue by mschwehl** [vy/log4j2-logstash-layout#9]
Thank you very much for this outstanding plugin. As spring-sleuth is becomming more popular two minor issues with your logging-plugin are present.

first: provide pid 
second: if one value is absent, then the plugin generates 'null' inside json whereas sleuth generates an empty string.

I hope you consider implementing these two minor enhancements

attacement: sleuth-pattern

https://github.com/spring-cloud-samples/sleuth-documentation-apps/blob/master/service1/src/main/resources/logback-spring.xml

**Comment by vy** [comment]
Hey @mschwehl, I am glad you liked the project. Though I am a bit confused by your questions. Let me elaborate that a bit:

1. Judging by [logback-spring.xml](https://github.com/spring-cloud-samples/sleuth-documentation-apps/blob/master/service1/src/main/resources/logback-spring.xml) you shared, `spring-cloud-samples` uses Logback for logging, though, as its name implies, `log4j2-logstash-layout` is a Log4j 2.x layout plugin. So I am totally puzzled here. That being said, I will address your questions assuming you want to use Log4j 2.x in combination with `log4j2-logstash-layout` plugin in `spring-cloud-examples`.
2. You want to expose *pid*. I think what you need is to just add a `pid` attribute referencing to `${env:PID}`. Just create a new template JSON having `"pid": "${env:PID}"` and you are done. (Why can't we ship it by default? Because we stick to [JSONEventLayoutV1](https://github.com/logstash/log4j-jsonevent-layout), which has a pre-defined structure.)
2. We are using the default Jackson `ObjectMapper` to read and write JSON. So you want to configure this mapper, say, to emit empty string on `null` entries. Correct?

**Comment by mschwehl** [comment]
Hello @vy,

Thank you for your quick response and sorry for the confusion here. 
My office is using an infrastructure using elkstack. One huge client is sending json messages in the 'sleuth' format and i want to produce the same output for my client using your log4j-json library

All works fine so far, thank you for providing this lib, it really fills a gap.


Refering to 2: 

My tester is 

```

        MDC.put("X-B3-TraceId", "tracID");
	logger.info("Test Message");

       // pattern.json
	{
			"message": "${json:message}",
			"severity": "${json:level}",
			"trace": "${json:mdc:X-B3-TraceId}",
			"nulltest": "${json:mdc:nulltest}",
			"pid": "${env:PID}"
	}
	//output
	{"message":"Test Message","severity":"INFO","trace":"tracID","nulltest":"null","pid":"${env:PID}"}

```
		
i think the PID is not evaluated, therefore my question i asked to you
		
Refering to 3:

I will have a look how to achieve the translation from 'null' to "" in nulltest using jackson. 

		
best regards
Martin.

**Comment by vy** [comment]
There was indeed a bug with resolving `null` MDC (context data) values. I pushed the fix. Would you mind testing it, please? If it works for you, I will make a new release.

Coming back to the PID discussion... I thought you already had an environment variable called `PID` passed to your Java application. My suggestion is to first [retrieve the PID in Java](https://stackoverflow.com/questions/35842/how-can-a-java-program-get-its-own-process-id) and then call `System.setProperty("PID", pid)`, which will make it accessible to Log4j lookups with `${env:PID}` variable.

**Comment by mschwehl** [comment]
I can confirm that the null-issue is fixed, thank you

Back to PID.  It was my misanderstanding, i was thinking that

https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/LogEvent.java

is providing the pid just like the ThreadId. I was wrong, thank you for pointing me to my error.

There are several ways to put the pid in the MDC. I will choose one of them and can go on with my coding.  If you don't mind i will close this issue after your next release (or you can do as well)

Bist wishes
Martin

**Comment by vy** [comment]
@mschwehl, great! Thanks for taking time to test it. I have just pushed the new release to Sonatype. v0.11 should appear in Maven Central momentarily.
